import { OVERVIEW_CARD, TOPIC_CARDS } from '../data/default-blocks'
import { PAPER_CHART_DATA } from '../data/paper-chart-data'
import { PAPER_NARRATIVE } from '../data/paper-narrative'
import { PAPER_METADATA, PAPER_SECTIONS } from '../data/paper-sections'
import type { StudyPackage } from './types'

function roundTo(value: number, digits: number): number {
  const factor = 10 ** digits
  return Math.round(value * factor) / factor
}

export const GEO_CENTRALIZATION_STUDY: StudyPackage = {
  id: 'geo-centralization',
  metadata: PAPER_METADATA,
  sections: PAPER_SECTIONS,
  narratives: PAPER_NARRATIVE,
  overviewCard: OVERVIEW_CARD,
  topicCards: TOPIC_CARDS,
  paperCharts: {
    'baseline-results': {
      data: PAPER_CHART_DATA['baseline-results'],
      description: 'Paper Figure 3 replay over 10,000 slots. One composite figure, four metrics, shared slot axis.',
      takeaway: 'Local block building pulls concentration upward faster and farther than external block building in the baseline setup.',
      metadata: ['1,000 validators', '10,000 slots', 'cost = 0.002 ETH', 'gamma = 2/3'],
      figureHref: '/paper-figures/fig3-baseline.png',
      figureLabel: 'Open original paper figure',
      datasetSummary: 'Derived directly from the full raw slot series in the checked-in baseline simulation outputs.',
      repoPaths: [
        'dashboard/simulations/baseline/SSP/cost_0.002/data.json',
        'dashboard/simulations/baseline/MSP/cost_0.002/data.json',
      ],
      publishedScenarioLinks: [
        {
          label: 'Open External replay',
          evaluation: 'Baseline',
          paradigm: 'External',
          result: 'cost_0.002',
        },
        {
          label: 'Open Local replay',
          evaluation: 'Baseline',
          paradigm: 'Local',
          result: 'cost_0.002',
        },
      ],
    },
    'se1-source-placement': {
      data: PAPER_CHART_DATA['se1-source-placement'],
      description: 'Paper Figure 4 replay for latency-aligned versus latency-misaligned information-source placement under both paradigms.',
      takeaway: 'Source placement flips the centralization gradient by paradigm: aligned sources strengthen local concentration, while misaligned suppliers strengthen external concentration.',
      metadata: ['1,000 validators', '10,000 slots', 'cost = 0.002 ETH', 'aligned vs misaligned sources'],
      figureHref: '/paper-figures/fig4-se1-sources.png',
      figureLabel: 'Open original paper figure',
      datasetSummary: 'Derived from the published SE1 source-placement datasets, sampled from the checked-in slot series for interactive comparison.',
      repoPaths: [
        'dashboard/simulations/heterogeneous_info/{SSP,MSP}/cost_0.002_latency_{latency-aligned,latency-misaligned}/data.json',
      ],
      publishedScenarioLinks: [
        {
          label: 'Open External aligned replay',
          evaluation: 'SE1-Information-Source-Placement-Effect',
          paradigm: 'External',
          result: 'latency-aligned',
        },
        {
          label: 'Open External misaligned replay',
          evaluation: 'SE1-Information-Source-Placement-Effect',
          paradigm: 'External',
          result: 'latency-misaligned',
        },
        {
          label: 'Open Local aligned replay',
          evaluation: 'SE1-Information-Source-Placement-Effect',
          paradigm: 'Local',
          result: 'latency-aligned',
        },
        {
          label: 'Open Local misaligned replay',
          evaluation: 'SE1-Information-Source-Placement-Effect',
          paradigm: 'Local',
          result: 'latency-misaligned',
        },
      ],
    },
    'se2-distribution': {
      data: PAPER_CHART_DATA['se2-distribution'],
      description: 'Paper Figure 5 replay for the heterogeneous validator-start experiment using the published 0.002 ETH migration-cost runs.',
      takeaway: 'Once validators start from an already concentrated geography, the two paradigms converge toward similarly compressed outcomes.',
      metadata: ['1,000 validators', '10,000 slots', 'cost = 0.002 ETH', 'heterogeneous validator start'],
      figureHref: '/paper-figures/fig5-se2-validators.png',
      figureLabel: 'Open original paper figure',
      datasetSummary: 'Derived from the published SE2 heterogeneous-validator datasets, sampled from the checked-in slot series for interactive comparison.',
      repoPaths: [
        'dashboard/simulations/heterogeneous_validators/{SSP,MSP}/cost_0.002_validators_heterogeneous/data.json',
      ],
      publishedScenarioLinks: [
        {
          label: 'Open External replay',
          evaluation: 'SE2-Validator-Distribution-Effect',
          paradigm: 'External',
          result: 'cost_0.002',
        },
        {
          label: 'Open Local replay',
          evaluation: 'SE2-Validator-Distribution-Effect',
          paradigm: 'Local',
          result: 'cost_0.002',
        },
      ],
    },
    'se3-joint': {
      data: PAPER_CHART_DATA['se3-joint'],
      description: 'Paper Figure 6 replay for the joint-heterogeneity experiment across aligned and misaligned source placements.',
      takeaway: 'The only temporary decentralization dip appears in the external misaligned case, and it reverses as the run continues.',
      metadata: ['1,000 validators', '10,000 slots', 'cost = 0.002 ETH', 'heterogeneous validators + source placement'],
      figureHref: '/paper-figures/fig6-se3-joint.png',
      figureLabel: 'Open original paper figure',
      datasetSummary: 'Derived from the published SE3 joint-heterogeneity datasets, sampled from the checked-in slot series for interactive comparison.',
      repoPaths: [
        'dashboard/simulations/heterogeneous_both/{SSP,MSP}/cost_0.002_latency_{latency-aligned,latency-misaligned}/data.json',
      ],
      publishedScenarioLinks: [
        {
          label: 'Open External aligned replay',
          evaluation: 'SE3-Joint-Heterogeneity',
          paradigm: 'External',
          result: 'latency-aligned',
        },
        {
          label: 'Open External misaligned replay',
          evaluation: 'SE3-Joint-Heterogeneity',
          paradigm: 'External',
          result: 'latency-misaligned',
        },
        {
          label: 'Open Local aligned replay',
          evaluation: 'SE3-Joint-Heterogeneity',
          paradigm: 'Local',
          result: 'latency-aligned',
        },
        {
          label: 'Open Local misaligned replay',
          evaluation: 'SE3-Joint-Heterogeneity',
          paradigm: 'Local',
          result: 'latency-misaligned',
        },
      ],
    },
    'se4a-attestation': {
      data: PAPER_CHART_DATA['se4a-attestation'],
      description: 'Paper Figure 7 replay across four attestation-threshold settings. One composite figure, four metrics, shared slot axis.',
      takeaway: 'Raising gamma increases external centralization pressure while reducing local centralization pressure.',
      metadata: ['1,000 validators', '10,000 slots', 'cost = 0.002 ETH', 'gamma in {1/3, 1/2, 2/3, 4/5}'],
      figureHref: '/paper-figures/fig7-se4a-gamma.png',
      figureLabel: 'Open original paper figure',
      datasetSummary: 'Derived directly from the full raw slot series in the checked-in attestation-threshold simulation outputs.',
      repoPaths: [
        'dashboard/simulations/different_gammas/{SSP,MSP}/cost_0.002_gamma_{0.3333,0.5,0.6667,0.8}/data.json',
      ],
      publishedScenarioLinks: [
        {
          label: 'Open External γ=2/3 replay',
          evaluation: 'SE4-Attestation-Threshold',
          paradigm: 'External',
          result: 'gamma_0.6667',
        },
        {
          label: 'Open Local γ=2/3 replay',
          evaluation: 'SE4-Attestation-Threshold',
          paradigm: 'Local',
          result: 'gamma_0.6667',
        },
      ],
    },
    'se4b-slots': {
      data: PAPER_CHART_DATA['se4b-slots'],
      description: 'Paper Figure 8 replay comparing 12-second and 6-second slots for both paradigms.',
      takeaway: 'Shorter slots mostly preserve the concentration trajectory while increasing the reward-variance gap.',
      metadata: ['1,000 validators', '10,000 slots', 'cost = 0.002 ETH', '12s vs 6s slots'],
      figureHref: '/paper-figures/fig8-se4b-slots.png',
      figureLabel: 'Open original paper figure',
      datasetSummary: 'Derived from the published baseline and EIP-7782 datasets, sampled from the checked-in slot series for interactive comparison.',
      repoPaths: [
        'dashboard/simulations/baseline/{SSP,MSP}/cost_0.002/data.json',
        'dashboard/simulations/eip7782/{SSP,MSP}/cost_0.002_delta_6000_cutoff_3000/data.json',
      ],
      publishedScenarioLinks: [
        {
          label: 'Open External 12s replay',
          evaluation: 'Baseline',
          paradigm: 'External',
          result: 'cost_0.002',
        },
        {
          label: 'Open External 6s replay',
          evaluation: 'SE4-EIP7782',
          paradigm: 'External',
          result: 'delta_6000_cutoff_3000',
        },
        {
          label: 'Open Local 12s replay',
          evaluation: 'Baseline',
          paradigm: 'Local',
          result: 'cost_0.002',
        },
        {
          label: 'Open Local 6s replay',
          evaluation: 'SE4-EIP7782',
          paradigm: 'Local',
          result: 'delta_6000_cutoff_3000',
        },
      ],
    },
  },
  navigation: {
    bestFirstStopIds: ['system-model', 'baseline-results', 'se4a-attestation', 'limitations'],
    pdfUrl: 'https://arxiv.org/pdf/2509.21475',
    htmlUrl: 'https://arxiv.org/html/2509.21475v2',
    sectionPageMap: {
      '§3': 4,
      '§3.1': 5,
      '§3.2': 5,
      '§3.1–3.2': 5,
      '§4': 6,
      '§4.1': 6,
      '§4.2': 7,
      '§4.3': 8,
      '§4.4': 8,
      '§4.5': 9,
      '§4.6.1': 10,
      '§4.6.2': 10,
      '§4.5 + App. E': 9,
      '§5': 11,
      '§5.1': 11,
      '§5.2': 11,
      '§5.3': 11,
      '§5.1-§5.2': 11,
      'App. E': 13,
      'App. E.3': 14,
      'App. E.4': 15,
    },
    sectionHtmlIdMap: {
      'system-model': 'S3',
      'simulation-design': 'S4.SS1',
      'baseline-results': 'S4.SS2',
      'se1-source-placement': 'S4.SS3',
      'se2-distribution': 'S4.SS4',
      'se3-joint': 'S4.SS5',
      'se4a-attestation': 'S4.SS6.SSS1',
      'se4b-slots': 'S4.SS6.SSS2',
      discussion: 'S5',
      limitations: 'S5.SS3',
    },
    appendices: [
      {
        id: 'appendix-a',
        label: 'Appendix A',
        summary: 'List of Google Cloud Platform regions.',
        url: 'https://arxiv.org/html/2509.21475v2#A1',
      },
      {
        id: 'appendix-b',
        label: 'Appendix B',
        summary: 'List of symbols used throughout the model.',
        url: 'https://arxiv.org/html/2509.21475v2#A2',
      },
      {
        id: 'appendix-c',
        label: 'Appendix C',
        summary: 'Marginal benefit distribution.',
        url: 'https://arxiv.org/html/2509.21475v2#A3',
      },
      {
        id: 'appendix-d',
        label: 'Appendix D',
        summary: 'Experiments with different scales.',
        url: 'https://arxiv.org/html/2509.21475v2#A4',
      },
      {
        id: 'appendix-e',
        label: 'Appendix E',
        summary: 'Migration costs.',
        url: 'https://arxiv.org/html/2509.21475v2#A5',
      },
      {
        id: 'appendix-f',
        label: 'Appendix F',
        summary: 'Baseline validator convergence locus.',
        url: 'https://arxiv.org/html/2509.21475v2#A6',
      },
      {
        id: 'appendix-g',
        label: 'Appendix G',
        summary: 'Joint heterogeneity validator convergence locus.',
        url: 'https://arxiv.org/html/2509.21475v2#A7',
      },
    ],
  },
  runtime: {
    defaultSimulationConfig: {
      paradigm: 'SSP',
      validators: 1000,
      slots: 1000,
      distribution: 'homogeneous',
      sourcePlacement: 'homogeneous',
      migrationCost: 0.0001,
      attestationThreshold: roundTo(2 / 3, 6),
      slotTime: 12,
      seed: 25873,
    },
    paperReferenceOverrides: {
      validators: 1000,
      slots: 10000,
      distribution: 'homogeneous',
      sourcePlacement: 'homogeneous',
      migrationCost: 0.002,
      attestationThreshold: roundTo(2 / 3, 6),
      slotTime: 12,
    },
    simulationPresets: {
      'baseline-ssp': {
        paradigm: 'SSP',
        validators: 1000,
        slots: 10000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.002,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
      },
      'baseline-msp': {
        paradigm: 'MSP',
        validators: 1000,
        slots: 10000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.002,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
      },
      'latency-aligned': {
        validators: 1000,
        slots: 10000,
        distribution: 'homogeneous',
        sourcePlacement: 'latency-aligned',
        migrationCost: 0.002,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
      },
      'latency-misaligned': {
        validators: 1000,
        slots: 10000,
        distribution: 'homogeneous',
        sourcePlacement: 'latency-misaligned',
        migrationCost: 0.002,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
      },
      'heterogeneous-start': {
        validators: 1000,
        slots: 10000,
        distribution: 'heterogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.002,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
      },
      'eip-7782': {
        validators: 1000,
        slots: 10000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.002,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 6,
      },
    },
    canonicalPrewarmConfigs: [
      {
        paradigm: 'SSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'MSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'SSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'latency-aligned',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'MSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'latency-aligned',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'SSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'latency-misaligned',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'MSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'latency-misaligned',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'SSP',
        validators: 1000,
        slots: 1000,
        distribution: 'heterogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'MSP',
        validators: 1000,
        slots: 1000,
        distribution: 'heterogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 12,
        seed: 25873,
      },
      {
        paradigm: 'SSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 6,
        seed: 25873,
      },
      {
        paradigm: 'MSP',
        validators: 1000,
        slots: 1000,
        distribution: 'homogeneous',
        sourcePlacement: 'homogeneous',
        migrationCost: 0.0001,
        attestationThreshold: roundTo(2 / 3, 6),
        slotTime: 6,
        seed: 25873,
      },
    ],
    sourceBlockRefs: [
      {
        label: 'arXiv:2509.21475',
        section: 'Geo-decentralization study',
        url: 'https://arxiv.org/abs/2509.21475',
      },
      {
        label: 'arXiv HTML',
        section: 'Source document',
        url: 'https://arxiv.org/html/2509.21475v2',
      },
      {
        label: 'Public dashboard',
        section: 'Published replays',
        url: 'https://geo-decentralization.github.io/',
      },
      {
        label: 'Simulation repository',
        section: 'Code and datasets',
        url: 'https://github.com/syang-ng/geographical-decentralization-simulation',
      },
    ],
  },
}
